#server
server:
  port: 8015


# Database
spring:
  datasource:
#   Oracle Database
#   driver-class-name: oracle.jdbc.OracleDriver
#   url: jdbc:oracle:thin:@toy.cwbdh2iaymjm.us-east-2.rds.amazonaws.com:1521/ORCL
#   username: admin
#   password: 12345678

    # H2 Database
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:


    # DEVTOOLS (DevToolsProperties)
    devtools:
      livereload:
        enabled: true
        port: 8015
compiler:
  automake:
    allow:
      when:
        app: running
ide:
  windowSystem: autoShowProcessPopup



  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug


